---
- name: Download and install docker
  yum: name=docker state=present

- name: Modify docker log driver
  replace:
    dest: /etc/sysconfig/docker
    regexp: '(\s+)*--log-driver=journald*'
    replace: '\1--log-driver=json-file'
    backup: yes

- name: Start the docker service
  service: name=docker state=started enabled=yes
